### ISSUE TITLE
[User] Allow unconfirmed users to sign in with limited functionality 

### ISSUE THREAD

**Issue by that-guy-iain** [getparthenon/monorepo#10]
## Problem

Sometimes users sign up with a fake email, not realising there is an email confirmation. Sometimes it is preferable to allow a user to sign in with an unconfirmed email while having limited features.

## Solution

Provide an option to allow unconfirmed logins and provide an option to configure which features are allowable with 

Provide code for feature flagging if the user is confirmed or not.

### Example

```yaml
parthenon:
  user:
    enabled: true
    email_confirmation: true
    login_without_confirmation: true
    confirmed_features:
       - email_send 
```
