### ISSUE TITLE
[User] Disable email confirmation

### ISSUE THREAD

**Issue by that-guy-iain** [getparthenon/monorepo#11]
## Problem

Sometimes email confirmation isn't needed or wanted.

## Solution

Provide an option to disable email confirmation requirement

### Example

```yaml
parthenon:
  user:
    enabled: true
    email_confirmation: false
```
